// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Achievement is the predicate function for achievement builders.
type Achievement func(*sql.Selector)

// Certification is the predicate function for certification builders.
type Certification func(*sql.Selector)

// Education is the predicate function for education builders.
type Education func(*sql.Selector)

// Experience is the predicate function for experience builders.
type Experience func(*sql.Selector)

// HeaderContactInfo is the predicate function for headercontactinfo builders.
type HeaderContactInfo func(*sql.Selector)

// Hobby is the predicate function for hobby builders.
type Hobby func(*sql.Selector)

// ProfessionalSummary is the predicate function for professionalsummary builders.
type ProfessionalSummary func(*sql.Selector)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// Resume is the predicate function for resume builders.
type Resume func(*sql.Selector)

// Skill is the predicate function for skill builders.
type Skill func(*sql.Selector)

// Template is the predicate function for template builders.
type Template func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
