// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"resume-builder-backend/ent/experience"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Experience is the model entity for the Experience schema.
type Experience struct {
	config
	// ID of the ent.
	ID           int `json:"id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Experience) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case experience.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Experience fields.
func (_m *Experience) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case experience.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Experience.
// This includes values selected through modifiers, order, etc.
func (_m *Experience) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Experience.
// Note that you need to call Experience.Unwrap() before calling this method if this Experience
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Experience) Update() *ExperienceUpdateOne {
	return NewExperienceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Experience entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Experience) Unwrap() *Experience {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Experience is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Experience) String() string {
	var builder strings.Builder
	builder.WriteString("Experience(")
	builder.WriteString(fmt.Sprintf("id=%v", _m.ID))
	builder.WriteByte(')')
	return builder.String()
}

// Experiences is a parsable slice of Experience.
type Experiences []*Experience
