// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"resume-builder-backend/ent/headercontactinfo"
	"resume-builder-backend/ent/resume"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// HeaderContactInfoCreate is the builder for creating a HeaderContactInfo entity.
type HeaderContactInfoCreate struct {
	config
	mutation *HeaderContactInfoMutation
	hooks    []Hook
}

// SetFullname sets the "fullname" field.
func (_c *HeaderContactInfoCreate) SetFullname(v string) *HeaderContactInfoCreate {
	_c.mutation.SetFullname(v)
	return _c
}

// SetProfessionalTitle sets the "professionalTitle" field.
func (_c *HeaderContactInfoCreate) SetProfessionalTitle(v string) *HeaderContactInfoCreate {
	_c.mutation.SetProfessionalTitle(v)
	return _c
}

// SetNillableProfessionalTitle sets the "professionalTitle" field if the given value is not nil.
func (_c *HeaderContactInfoCreate) SetNillableProfessionalTitle(v *string) *HeaderContactInfoCreate {
	if v != nil {
		_c.SetProfessionalTitle(*v)
	}
	return _c
}

// SetAddress sets the "address" field.
func (_c *HeaderContactInfoCreate) SetAddress(v string) *HeaderContactInfoCreate {
	_c.mutation.SetAddress(v)
	return _c
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_c *HeaderContactInfoCreate) SetNillableAddress(v *string) *HeaderContactInfoCreate {
	if v != nil {
		_c.SetAddress(*v)
	}
	return _c
}

// SetPhone sets the "phone" field.
func (_c *HeaderContactInfoCreate) SetPhone(v string) *HeaderContactInfoCreate {
	_c.mutation.SetPhone(v)
	return _c
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_c *HeaderContactInfoCreate) SetNillablePhone(v *string) *HeaderContactInfoCreate {
	if v != nil {
		_c.SetPhone(*v)
	}
	return _c
}

// SetEmail sets the "email" field.
func (_c *HeaderContactInfoCreate) SetEmail(v string) *HeaderContactInfoCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetCity sets the "city" field.
func (_c *HeaderContactInfoCreate) SetCity(v string) *HeaderContactInfoCreate {
	_c.mutation.SetCity(v)
	return _c
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (_c *HeaderContactInfoCreate) SetNillableCity(v *string) *HeaderContactInfoCreate {
	if v != nil {
		_c.SetCity(*v)
	}
	return _c
}

// SetState sets the "state" field.
func (_c *HeaderContactInfoCreate) SetState(v string) *HeaderContactInfoCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_c *HeaderContactInfoCreate) SetNillableState(v *string) *HeaderContactInfoCreate {
	if v != nil {
		_c.SetState(*v)
	}
	return _c
}

// SetZipCode sets the "zipCode" field.
func (_c *HeaderContactInfoCreate) SetZipCode(v string) *HeaderContactInfoCreate {
	_c.mutation.SetZipCode(v)
	return _c
}

// SetNillableZipCode sets the "zipCode" field if the given value is not nil.
func (_c *HeaderContactInfoCreate) SetNillableZipCode(v *string) *HeaderContactInfoCreate {
	if v != nil {
		_c.SetZipCode(*v)
	}
	return _c
}

// SetCountry sets the "country" field.
func (_c *HeaderContactInfoCreate) SetCountry(v string) *HeaderContactInfoCreate {
	_c.mutation.SetCountry(v)
	return _c
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_c *HeaderContactInfoCreate) SetNillableCountry(v *string) *HeaderContactInfoCreate {
	if v != nil {
		_c.SetCountry(*v)
	}
	return _c
}

// SetLinkedinUrl sets the "linkedinUrl" field.
func (_c *HeaderContactInfoCreate) SetLinkedinUrl(v string) *HeaderContactInfoCreate {
	_c.mutation.SetLinkedinUrl(v)
	return _c
}

// SetNillableLinkedinUrl sets the "linkedinUrl" field if the given value is not nil.
func (_c *HeaderContactInfoCreate) SetNillableLinkedinUrl(v *string) *HeaderContactInfoCreate {
	if v != nil {
		_c.SetLinkedinUrl(*v)
	}
	return _c
}

// SetGithubUrl sets the "githubUrl" field.
func (_c *HeaderContactInfoCreate) SetGithubUrl(v string) *HeaderContactInfoCreate {
	_c.mutation.SetGithubUrl(v)
	return _c
}

// SetNillableGithubUrl sets the "githubUrl" field if the given value is not nil.
func (_c *HeaderContactInfoCreate) SetNillableGithubUrl(v *string) *HeaderContactInfoCreate {
	if v != nil {
		_c.SetGithubUrl(*v)
	}
	return _c
}

// SetPortfolioUrl sets the "portfolioUrl" field.
func (_c *HeaderContactInfoCreate) SetPortfolioUrl(v string) *HeaderContactInfoCreate {
	_c.mutation.SetPortfolioUrl(v)
	return _c
}

// SetNillablePortfolioUrl sets the "portfolioUrl" field if the given value is not nil.
func (_c *HeaderContactInfoCreate) SetNillablePortfolioUrl(v *string) *HeaderContactInfoCreate {
	if v != nil {
		_c.SetPortfolioUrl(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *HeaderContactInfoCreate) SetID(v uuid.UUID) *HeaderContactInfoCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *HeaderContactInfoCreate) SetNillableID(v *uuid.UUID) *HeaderContactInfoCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetResumeID sets the "resume" edge to the Resume entity by ID.
func (_c *HeaderContactInfoCreate) SetResumeID(id uuid.UUID) *HeaderContactInfoCreate {
	_c.mutation.SetResumeID(id)
	return _c
}

// SetResume sets the "resume" edge to the Resume entity.
func (_c *HeaderContactInfoCreate) SetResume(v *Resume) *HeaderContactInfoCreate {
	return _c.SetResumeID(v.ID)
}

// Mutation returns the HeaderContactInfoMutation object of the builder.
func (_c *HeaderContactInfoCreate) Mutation() *HeaderContactInfoMutation {
	return _c.mutation
}

// Save creates the HeaderContactInfo in the database.
func (_c *HeaderContactInfoCreate) Save(ctx context.Context) (*HeaderContactInfo, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *HeaderContactInfoCreate) SaveX(ctx context.Context) *HeaderContactInfo {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HeaderContactInfoCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HeaderContactInfoCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *HeaderContactInfoCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := headercontactinfo.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *HeaderContactInfoCreate) check() error {
	if _, ok := _c.mutation.Fullname(); !ok {
		return &ValidationError{Name: "fullname", err: errors.New(`ent: missing required field "HeaderContactInfo.fullname"`)}
	}
	if v, ok := _c.mutation.Fullname(); ok {
		if err := headercontactinfo.FullnameValidator(v); err != nil {
			return &ValidationError{Name: "fullname", err: fmt.Errorf(`ent: validator failed for field "HeaderContactInfo.fullname": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "HeaderContactInfo.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := headercontactinfo.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "HeaderContactInfo.email": %w`, err)}
		}
	}
	if len(_c.mutation.ResumeIDs()) == 0 {
		return &ValidationError{Name: "resume", err: errors.New(`ent: missing required edge "HeaderContactInfo.resume"`)}
	}
	return nil
}

func (_c *HeaderContactInfoCreate) sqlSave(ctx context.Context) (*HeaderContactInfo, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *HeaderContactInfoCreate) createSpec() (*HeaderContactInfo, *sqlgraph.CreateSpec) {
	var (
		_node = &HeaderContactInfo{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(headercontactinfo.Table, sqlgraph.NewFieldSpec(headercontactinfo.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Fullname(); ok {
		_spec.SetField(headercontactinfo.FieldFullname, field.TypeString, value)
		_node.Fullname = value
	}
	if value, ok := _c.mutation.ProfessionalTitle(); ok {
		_spec.SetField(headercontactinfo.FieldProfessionalTitle, field.TypeString, value)
		_node.ProfessionalTitle = value
	}
	if value, ok := _c.mutation.Address(); ok {
		_spec.SetField(headercontactinfo.FieldAddress, field.TypeString, value)
		_node.Address = value
	}
	if value, ok := _c.mutation.Phone(); ok {
		_spec.SetField(headercontactinfo.FieldPhone, field.TypeString, value)
		_node.Phone = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(headercontactinfo.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.City(); ok {
		_spec.SetField(headercontactinfo.FieldCity, field.TypeString, value)
		_node.City = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(headercontactinfo.FieldState, field.TypeString, value)
		_node.State = value
	}
	if value, ok := _c.mutation.ZipCode(); ok {
		_spec.SetField(headercontactinfo.FieldZipCode, field.TypeString, value)
		_node.ZipCode = value
	}
	if value, ok := _c.mutation.Country(); ok {
		_spec.SetField(headercontactinfo.FieldCountry, field.TypeString, value)
		_node.Country = value
	}
	if value, ok := _c.mutation.LinkedinUrl(); ok {
		_spec.SetField(headercontactinfo.FieldLinkedinUrl, field.TypeString, value)
		_node.LinkedinUrl = value
	}
	if value, ok := _c.mutation.GithubUrl(); ok {
		_spec.SetField(headercontactinfo.FieldGithubUrl, field.TypeString, value)
		_node.GithubUrl = value
	}
	if value, ok := _c.mutation.PortfolioUrl(); ok {
		_spec.SetField(headercontactinfo.FieldPortfolioUrl, field.TypeString, value)
		_node.PortfolioUrl = value
	}
	if nodes := _c.mutation.ResumeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   headercontactinfo.ResumeTable,
			Columns: []string{headercontactinfo.ResumeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resume.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.resume_header_contanct_info = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// HeaderContactInfoCreateBulk is the builder for creating many HeaderContactInfo entities in bulk.
type HeaderContactInfoCreateBulk struct {
	config
	err      error
	builders []*HeaderContactInfoCreate
}

// Save creates the HeaderContactInfo entities in the database.
func (_c *HeaderContactInfoCreateBulk) Save(ctx context.Context) ([]*HeaderContactInfo, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*HeaderContactInfo, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HeaderContactInfoMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *HeaderContactInfoCreateBulk) SaveX(ctx context.Context) []*HeaderContactInfo {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HeaderContactInfoCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HeaderContactInfoCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
