// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"resume-builder-backend/ent/predicate"
	"resume-builder-backend/ent/professionalsummary"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProfessionalSummaryUpdate is the builder for updating ProfessionalSummary entities.
type ProfessionalSummaryUpdate struct {
	config
	hooks    []Hook
	mutation *ProfessionalSummaryMutation
}

// Where appends a list predicates to the ProfessionalSummaryUpdate builder.
func (_u *ProfessionalSummaryUpdate) Where(ps ...predicate.ProfessionalSummary) *ProfessionalSummaryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// Mutation returns the ProfessionalSummaryMutation object of the builder.
func (_u *ProfessionalSummaryUpdate) Mutation() *ProfessionalSummaryMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProfessionalSummaryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProfessionalSummaryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProfessionalSummaryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProfessionalSummaryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ProfessionalSummaryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(professionalsummary.Table, professionalsummary.Columns, sqlgraph.NewFieldSpec(professionalsummary.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{professionalsummary.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProfessionalSummaryUpdateOne is the builder for updating a single ProfessionalSummary entity.
type ProfessionalSummaryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProfessionalSummaryMutation
}

// Mutation returns the ProfessionalSummaryMutation object of the builder.
func (_u *ProfessionalSummaryUpdateOne) Mutation() *ProfessionalSummaryMutation {
	return _u.mutation
}

// Where appends a list predicates to the ProfessionalSummaryUpdate builder.
func (_u *ProfessionalSummaryUpdateOne) Where(ps ...predicate.ProfessionalSummary) *ProfessionalSummaryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProfessionalSummaryUpdateOne) Select(field string, fields ...string) *ProfessionalSummaryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProfessionalSummary entity.
func (_u *ProfessionalSummaryUpdateOne) Save(ctx context.Context) (*ProfessionalSummary, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProfessionalSummaryUpdateOne) SaveX(ctx context.Context) *ProfessionalSummary {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProfessionalSummaryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProfessionalSummaryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ProfessionalSummaryUpdateOne) sqlSave(ctx context.Context) (_node *ProfessionalSummary, err error) {
	_spec := sqlgraph.NewUpdateSpec(professionalsummary.Table, professionalsummary.Columns, sqlgraph.NewFieldSpec(professionalsummary.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProfessionalSummary.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, professionalsummary.FieldID)
		for _, f := range fields {
			if !professionalsummary.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != professionalsummary.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &ProfessionalSummary{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{professionalsummary.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
