// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"resume-builder-backend/ent/professionalsummary"
	"resume-builder-backend/ent/resume"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ProfessionalSummary is the model entity for the ProfessionalSummary schema.
type ProfessionalSummary struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// ResumeId holds the value of the "resumeId" field.
	ResumeId uuid.UUID `json:"resumeId,omitempty"`
	// Summary holds the value of the "summary" field.
	Summary string `json:"summary,omitempty"`
	// YearsOfExperience holds the value of the "yearsOfExperience" field.
	YearsOfExperience *int `json:"yearsOfExperience,omitempty"`
	// KeyStrengths holds the value of the "keyStrengths" field.
	KeyStrengths []string `json:"keyStrengths,omitempty"`
	// CareerObjective holds the value of the "careerObjective" field.
	CareerObjective string `json:"careerObjective,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProfessionalSummaryQuery when eager-loading is set.
	Edges        ProfessionalSummaryEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ProfessionalSummaryEdges holds the relations/edges for other nodes in the graph.
type ProfessionalSummaryEdges struct {
	// Resume holds the value of the resume edge.
	Resume *Resume `json:"resume,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ResumeOrErr returns the Resume value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProfessionalSummaryEdges) ResumeOrErr() (*Resume, error) {
	if e.Resume != nil {
		return e.Resume, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: resume.Label}
	}
	return nil, &NotLoadedError{edge: "resume"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProfessionalSummary) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case professionalsummary.FieldKeyStrengths:
			values[i] = new([]byte)
		case professionalsummary.FieldYearsOfExperience:
			values[i] = new(sql.NullInt64)
		case professionalsummary.FieldSummary, professionalsummary.FieldCareerObjective:
			values[i] = new(sql.NullString)
		case professionalsummary.FieldID, professionalsummary.FieldResumeId:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProfessionalSummary fields.
func (_m *ProfessionalSummary) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case professionalsummary.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case professionalsummary.FieldResumeId:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field resumeId", values[i])
			} else if value != nil {
				_m.ResumeId = *value
			}
		case professionalsummary.FieldSummary:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field summary", values[i])
			} else if value.Valid {
				_m.Summary = value.String
			}
		case professionalsummary.FieldYearsOfExperience:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field yearsOfExperience", values[i])
			} else if value.Valid {
				_m.YearsOfExperience = new(int)
				*_m.YearsOfExperience = int(value.Int64)
			}
		case professionalsummary.FieldKeyStrengths:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field keyStrengths", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.KeyStrengths); err != nil {
					return fmt.Errorf("unmarshal field keyStrengths: %w", err)
				}
			}
		case professionalsummary.FieldCareerObjective:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field careerObjective", values[i])
			} else if value.Valid {
				_m.CareerObjective = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProfessionalSummary.
// This includes values selected through modifiers, order, etc.
func (_m *ProfessionalSummary) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryResume queries the "resume" edge of the ProfessionalSummary entity.
func (_m *ProfessionalSummary) QueryResume() *ResumeQuery {
	return NewProfessionalSummaryClient(_m.config).QueryResume(_m)
}

// Update returns a builder for updating this ProfessionalSummary.
// Note that you need to call ProfessionalSummary.Unwrap() before calling this method if this ProfessionalSummary
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProfessionalSummary) Update() *ProfessionalSummaryUpdateOne {
	return NewProfessionalSummaryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProfessionalSummary entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProfessionalSummary) Unwrap() *ProfessionalSummary {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProfessionalSummary is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProfessionalSummary) String() string {
	var builder strings.Builder
	builder.WriteString("ProfessionalSummary(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("resumeId=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResumeId))
	builder.WriteString(", ")
	builder.WriteString("summary=")
	builder.WriteString(_m.Summary)
	builder.WriteString(", ")
	if v := _m.YearsOfExperience; v != nil {
		builder.WriteString("yearsOfExperience=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("keyStrengths=")
	builder.WriteString(fmt.Sprintf("%v", _m.KeyStrengths))
	builder.WriteString(", ")
	builder.WriteString("careerObjective=")
	builder.WriteString(_m.CareerObjective)
	builder.WriteByte(')')
	return builder.String()
}

// ProfessionalSummaries is a parsable slice of ProfessionalSummary.
type ProfessionalSummaries []*ProfessionalSummary
