// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"resume-builder-backend/ent/predicate"
	"resume-builder-backend/ent/resume"
	"resume-builder-backend/ent/template"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// TemplateUpdate is the builder for updating Template entities.
type TemplateUpdate struct {
	config
	hooks    []Hook
	mutation *TemplateMutation
}

// Where appends a list predicates to the TemplateUpdate builder.
func (_u *TemplateUpdate) Where(ps ...predicate.Template) *TemplateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *TemplateUpdate) SetName(v string) *TemplateUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TemplateUpdate) SetNillableName(v *string) *TemplateUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TemplateUpdate) SetDescription(v string) *TemplateUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TemplateUpdate) SetNillableDescription(v *string) *TemplateUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TemplateUpdate) ClearDescription() *TemplateUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetHtmlTemplate sets the "htmlTemplate" field.
func (_u *TemplateUpdate) SetHtmlTemplate(v string) *TemplateUpdate {
	_u.mutation.SetHtmlTemplate(v)
	return _u
}

// SetNillableHtmlTemplate sets the "htmlTemplate" field if the given value is not nil.
func (_u *TemplateUpdate) SetNillableHtmlTemplate(v *string) *TemplateUpdate {
	if v != nil {
		_u.SetHtmlTemplate(*v)
	}
	return _u
}

// SetCssStyles sets the "cssStyles" field.
func (_u *TemplateUpdate) SetCssStyles(v string) *TemplateUpdate {
	_u.mutation.SetCssStyles(v)
	return _u
}

// SetNillableCssStyles sets the "cssStyles" field if the given value is not nil.
func (_u *TemplateUpdate) SetNillableCssStyles(v *string) *TemplateUpdate {
	if v != nil {
		_u.SetCssStyles(*v)
	}
	return _u
}

// SetIsActive sets the "isActive" field.
func (_u *TemplateUpdate) SetIsActive(v bool) *TemplateUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "isActive" field if the given value is not nil.
func (_u *TemplateUpdate) SetNillableIsActive(v *bool) *TemplateUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetPreviewImage sets the "previewImage" field.
func (_u *TemplateUpdate) SetPreviewImage(v string) *TemplateUpdate {
	_u.mutation.SetPreviewImage(v)
	return _u
}

// SetNillablePreviewImage sets the "previewImage" field if the given value is not nil.
func (_u *TemplateUpdate) SetNillablePreviewImage(v *string) *TemplateUpdate {
	if v != nil {
		_u.SetPreviewImage(*v)
	}
	return _u
}

// ClearPreviewImage clears the value of the "previewImage" field.
func (_u *TemplateUpdate) ClearPreviewImage() *TemplateUpdate {
	_u.mutation.ClearPreviewImage()
	return _u
}

// AddResumeIDs adds the "resumes" edge to the Resume entity by IDs.
func (_u *TemplateUpdate) AddResumeIDs(ids ...uuid.UUID) *TemplateUpdate {
	_u.mutation.AddResumeIDs(ids...)
	return _u
}

// AddResumes adds the "resumes" edges to the Resume entity.
func (_u *TemplateUpdate) AddResumes(v ...*Resume) *TemplateUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddResumeIDs(ids...)
}

// Mutation returns the TemplateMutation object of the builder.
func (_u *TemplateUpdate) Mutation() *TemplateMutation {
	return _u.mutation
}

// ClearResumes clears all "resumes" edges to the Resume entity.
func (_u *TemplateUpdate) ClearResumes() *TemplateUpdate {
	_u.mutation.ClearResumes()
	return _u
}

// RemoveResumeIDs removes the "resumes" edge to Resume entities by IDs.
func (_u *TemplateUpdate) RemoveResumeIDs(ids ...uuid.UUID) *TemplateUpdate {
	_u.mutation.RemoveResumeIDs(ids...)
	return _u
}

// RemoveResumes removes "resumes" edges to Resume entities.
func (_u *TemplateUpdate) RemoveResumes(v ...*Resume) *TemplateUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveResumeIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TemplateUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TemplateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TemplateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TemplateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TemplateUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := template.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Template.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HtmlTemplate(); ok {
		if err := template.HtmlTemplateValidator(v); err != nil {
			return &ValidationError{Name: "htmlTemplate", err: fmt.Errorf(`ent: validator failed for field "Template.htmlTemplate": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CssStyles(); ok {
		if err := template.CssStylesValidator(v); err != nil {
			return &ValidationError{Name: "cssStyles", err: fmt.Errorf(`ent: validator failed for field "Template.cssStyles": %w`, err)}
		}
	}
	return nil
}

func (_u *TemplateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(template.Table, template.Columns, sqlgraph.NewFieldSpec(template.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(template.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(template.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(template.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.HtmlTemplate(); ok {
		_spec.SetField(template.FieldHtmlTemplate, field.TypeString, value)
	}
	if value, ok := _u.mutation.CssStyles(); ok {
		_spec.SetField(template.FieldCssStyles, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(template.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PreviewImage(); ok {
		_spec.SetField(template.FieldPreviewImage, field.TypeString, value)
	}
	if _u.mutation.PreviewImageCleared() {
		_spec.ClearField(template.FieldPreviewImage, field.TypeString)
	}
	if _u.mutation.ResumesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   template.ResumesTable,
			Columns: []string{template.ResumesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resume.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedResumesIDs(); len(nodes) > 0 && !_u.mutation.ResumesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   template.ResumesTable,
			Columns: []string{template.ResumesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resume.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ResumesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   template.ResumesTable,
			Columns: []string{template.ResumesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resume.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{template.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TemplateUpdateOne is the builder for updating a single Template entity.
type TemplateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TemplateMutation
}

// SetName sets the "name" field.
func (_u *TemplateUpdateOne) SetName(v string) *TemplateUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TemplateUpdateOne) SetNillableName(v *string) *TemplateUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TemplateUpdateOne) SetDescription(v string) *TemplateUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TemplateUpdateOne) SetNillableDescription(v *string) *TemplateUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TemplateUpdateOne) ClearDescription() *TemplateUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetHtmlTemplate sets the "htmlTemplate" field.
func (_u *TemplateUpdateOne) SetHtmlTemplate(v string) *TemplateUpdateOne {
	_u.mutation.SetHtmlTemplate(v)
	return _u
}

// SetNillableHtmlTemplate sets the "htmlTemplate" field if the given value is not nil.
func (_u *TemplateUpdateOne) SetNillableHtmlTemplate(v *string) *TemplateUpdateOne {
	if v != nil {
		_u.SetHtmlTemplate(*v)
	}
	return _u
}

// SetCssStyles sets the "cssStyles" field.
func (_u *TemplateUpdateOne) SetCssStyles(v string) *TemplateUpdateOne {
	_u.mutation.SetCssStyles(v)
	return _u
}

// SetNillableCssStyles sets the "cssStyles" field if the given value is not nil.
func (_u *TemplateUpdateOne) SetNillableCssStyles(v *string) *TemplateUpdateOne {
	if v != nil {
		_u.SetCssStyles(*v)
	}
	return _u
}

// SetIsActive sets the "isActive" field.
func (_u *TemplateUpdateOne) SetIsActive(v bool) *TemplateUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "isActive" field if the given value is not nil.
func (_u *TemplateUpdateOne) SetNillableIsActive(v *bool) *TemplateUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetPreviewImage sets the "previewImage" field.
func (_u *TemplateUpdateOne) SetPreviewImage(v string) *TemplateUpdateOne {
	_u.mutation.SetPreviewImage(v)
	return _u
}

// SetNillablePreviewImage sets the "previewImage" field if the given value is not nil.
func (_u *TemplateUpdateOne) SetNillablePreviewImage(v *string) *TemplateUpdateOne {
	if v != nil {
		_u.SetPreviewImage(*v)
	}
	return _u
}

// ClearPreviewImage clears the value of the "previewImage" field.
func (_u *TemplateUpdateOne) ClearPreviewImage() *TemplateUpdateOne {
	_u.mutation.ClearPreviewImage()
	return _u
}

// AddResumeIDs adds the "resumes" edge to the Resume entity by IDs.
func (_u *TemplateUpdateOne) AddResumeIDs(ids ...uuid.UUID) *TemplateUpdateOne {
	_u.mutation.AddResumeIDs(ids...)
	return _u
}

// AddResumes adds the "resumes" edges to the Resume entity.
func (_u *TemplateUpdateOne) AddResumes(v ...*Resume) *TemplateUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddResumeIDs(ids...)
}

// Mutation returns the TemplateMutation object of the builder.
func (_u *TemplateUpdateOne) Mutation() *TemplateMutation {
	return _u.mutation
}

// ClearResumes clears all "resumes" edges to the Resume entity.
func (_u *TemplateUpdateOne) ClearResumes() *TemplateUpdateOne {
	_u.mutation.ClearResumes()
	return _u
}

// RemoveResumeIDs removes the "resumes" edge to Resume entities by IDs.
func (_u *TemplateUpdateOne) RemoveResumeIDs(ids ...uuid.UUID) *TemplateUpdateOne {
	_u.mutation.RemoveResumeIDs(ids...)
	return _u
}

// RemoveResumes removes "resumes" edges to Resume entities.
func (_u *TemplateUpdateOne) RemoveResumes(v ...*Resume) *TemplateUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveResumeIDs(ids...)
}

// Where appends a list predicates to the TemplateUpdate builder.
func (_u *TemplateUpdateOne) Where(ps ...predicate.Template) *TemplateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TemplateUpdateOne) Select(field string, fields ...string) *TemplateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Template entity.
func (_u *TemplateUpdateOne) Save(ctx context.Context) (*Template, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TemplateUpdateOne) SaveX(ctx context.Context) *Template {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TemplateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TemplateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TemplateUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := template.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Template.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HtmlTemplate(); ok {
		if err := template.HtmlTemplateValidator(v); err != nil {
			return &ValidationError{Name: "htmlTemplate", err: fmt.Errorf(`ent: validator failed for field "Template.htmlTemplate": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CssStyles(); ok {
		if err := template.CssStylesValidator(v); err != nil {
			return &ValidationError{Name: "cssStyles", err: fmt.Errorf(`ent: validator failed for field "Template.cssStyles": %w`, err)}
		}
	}
	return nil
}

func (_u *TemplateUpdateOne) sqlSave(ctx context.Context) (_node *Template, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(template.Table, template.Columns, sqlgraph.NewFieldSpec(template.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Template.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, template.FieldID)
		for _, f := range fields {
			if !template.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != template.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(template.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(template.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(template.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.HtmlTemplate(); ok {
		_spec.SetField(template.FieldHtmlTemplate, field.TypeString, value)
	}
	if value, ok := _u.mutation.CssStyles(); ok {
		_spec.SetField(template.FieldCssStyles, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(template.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PreviewImage(); ok {
		_spec.SetField(template.FieldPreviewImage, field.TypeString, value)
	}
	if _u.mutation.PreviewImageCleared() {
		_spec.ClearField(template.FieldPreviewImage, field.TypeString)
	}
	if _u.mutation.ResumesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   template.ResumesTable,
			Columns: []string{template.ResumesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resume.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedResumesIDs(); len(nodes) > 0 && !_u.mutation.ResumesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   template.ResumesTable,
			Columns: []string{template.ResumesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resume.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ResumesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   template.ResumesTable,
			Columns: []string{template.ResumesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resume.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Template{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{template.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
