// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"resume-builder-backend/ent/resume"
	"resume-builder-backend/ent/template"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// TemplateCreate is the builder for creating a Template entity.
type TemplateCreate struct {
	config
	mutation *TemplateMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *TemplateCreate) SetName(v string) *TemplateCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *TemplateCreate) SetDescription(v string) *TemplateCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *TemplateCreate) SetNillableDescription(v *string) *TemplateCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetHtmlTemplate sets the "htmlTemplate" field.
func (_c *TemplateCreate) SetHtmlTemplate(v string) *TemplateCreate {
	_c.mutation.SetHtmlTemplate(v)
	return _c
}

// SetCssStyles sets the "cssStyles" field.
func (_c *TemplateCreate) SetCssStyles(v string) *TemplateCreate {
	_c.mutation.SetCssStyles(v)
	return _c
}

// SetIsActive sets the "isActive" field.
func (_c *TemplateCreate) SetIsActive(v bool) *TemplateCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "isActive" field if the given value is not nil.
func (_c *TemplateCreate) SetNillableIsActive(v *bool) *TemplateCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetPreviewImage sets the "previewImage" field.
func (_c *TemplateCreate) SetPreviewImage(v string) *TemplateCreate {
	_c.mutation.SetPreviewImage(v)
	return _c
}

// SetNillablePreviewImage sets the "previewImage" field if the given value is not nil.
func (_c *TemplateCreate) SetNillablePreviewImage(v *string) *TemplateCreate {
	if v != nil {
		_c.SetPreviewImage(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TemplateCreate) SetID(v uuid.UUID) *TemplateCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *TemplateCreate) SetNillableID(v *uuid.UUID) *TemplateCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddResumeIDs adds the "resumes" edge to the Resume entity by IDs.
func (_c *TemplateCreate) AddResumeIDs(ids ...uuid.UUID) *TemplateCreate {
	_c.mutation.AddResumeIDs(ids...)
	return _c
}

// AddResumes adds the "resumes" edges to the Resume entity.
func (_c *TemplateCreate) AddResumes(v ...*Resume) *TemplateCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddResumeIDs(ids...)
}

// Mutation returns the TemplateMutation object of the builder.
func (_c *TemplateCreate) Mutation() *TemplateMutation {
	return _c.mutation
}

// Save creates the Template in the database.
func (_c *TemplateCreate) Save(ctx context.Context) (*Template, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TemplateCreate) SaveX(ctx context.Context) *Template {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TemplateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TemplateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TemplateCreate) defaults() {
	if _, ok := _c.mutation.IsActive(); !ok {
		v := template.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := template.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TemplateCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Template.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := template.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Template.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.HtmlTemplate(); !ok {
		return &ValidationError{Name: "htmlTemplate", err: errors.New(`ent: missing required field "Template.htmlTemplate"`)}
	}
	if v, ok := _c.mutation.HtmlTemplate(); ok {
		if err := template.HtmlTemplateValidator(v); err != nil {
			return &ValidationError{Name: "htmlTemplate", err: fmt.Errorf(`ent: validator failed for field "Template.htmlTemplate": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CssStyles(); !ok {
		return &ValidationError{Name: "cssStyles", err: errors.New(`ent: missing required field "Template.cssStyles"`)}
	}
	if v, ok := _c.mutation.CssStyles(); ok {
		if err := template.CssStylesValidator(v); err != nil {
			return &ValidationError{Name: "cssStyles", err: fmt.Errorf(`ent: validator failed for field "Template.cssStyles": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "isActive", err: errors.New(`ent: missing required field "Template.isActive"`)}
	}
	return nil
}

func (_c *TemplateCreate) sqlSave(ctx context.Context) (*Template, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TemplateCreate) createSpec() (*Template, *sqlgraph.CreateSpec) {
	var (
		_node = &Template{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(template.Table, sqlgraph.NewFieldSpec(template.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(template.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(template.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.HtmlTemplate(); ok {
		_spec.SetField(template.FieldHtmlTemplate, field.TypeString, value)
		_node.HtmlTemplate = value
	}
	if value, ok := _c.mutation.CssStyles(); ok {
		_spec.SetField(template.FieldCssStyles, field.TypeString, value)
		_node.CssStyles = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(template.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.PreviewImage(); ok {
		_spec.SetField(template.FieldPreviewImage, field.TypeString, value)
		_node.PreviewImage = value
	}
	if nodes := _c.mutation.ResumesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   template.ResumesTable,
			Columns: []string{template.ResumesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resume.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TemplateCreateBulk is the builder for creating many Template entities in bulk.
type TemplateCreateBulk struct {
	config
	err      error
	builders []*TemplateCreate
}

// Save creates the Template entities in the database.
func (_c *TemplateCreateBulk) Save(ctx context.Context) ([]*Template, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Template, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TemplateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TemplateCreateBulk) SaveX(ctx context.Context) []*Template {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TemplateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TemplateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
